---
title: "ISYE 6739 Homework 1"
author: "Patrick Gardocki"
date: "2023-05-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 2-19

a)  $A' = 3,5,6,8$
b)  $A \cap B = 1,2$
c)  $(A \cap B ) \cup  C = 1,2,3,4,5$
d)  $(B \cup C)' = 7,8$
e)  $(A \cap B)' \cup C = 2$

## 2-81

a)  $P(A) = \frac{52^8}{62^8} = 0.2448461$
b)  $P(B) = \frac{10^8}{62^8} = 4.580011e-7$
c)  $P(B\ge1) = 1 - P(A) = 0.7551539$
d)  $P(B=2) =  \frac{{8\choose6} \times 10^2 \times 52^6}{62^8} = 0.2535389$


## 2-90

a)  $P(A) = \frac{{5\choose1} \times 36^5}{36^6} = 5/36 \approx 0.138889$
b)  $P(B) = 1$
c)  $$P(A \cap B) = P(A) \cdot P(B) = \frac{25}{36^2} \approx 0.019290 $$
d)  $$P(A \cup B) =  P(A) + P(B) - P(A \cap B) = \frac{5}{36} + \frac{5}{36} - \frac{25}{36^2} = 0.258487 $$


## 2-141

a) $P(A|B') = \frac{P(A'\cap B')}{P(B')} = \frac{P(A'\cap B')}{1-P(B)}= \frac{P(A)}{1- P(B)}$
a) $P(A' \cap B) = $
a) $P(A=2|B\ge1) = $

## 2-179

## #2

$${13\choose1}{4\choose3}{12\choose2}{4\choose1}^2 = 54,912  $$

```{r}
choose(13,1) * choose(4,3)*choose(12,2)*choose(4,1)^2
```
